#include <stdio.h>
#include <stdlib.h>

const char* stock_count_header(const char* working_dir) {
    const char* CSS = "<!DOCTYPE html>\n"
                      "<html lang=\"en\">\n"
                      "<head>\n"
                      "    <meta charset=\"UTF-8\">\n"
                      "    <title>Title</title>\n"
                      "    <link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css?family=Sofia\">\n"
                      "    <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\n"
                      "    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\n"
                      "    <link href=\"https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300..800;1,300..800&family=PT+Sans:ital,wght@0,400;0,700;1,400;1,700&display=swap\" rel=\"stylesheet\">\n"
                      "    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css\" integrity=\"sha512-Evv84Mr4kqVGRNSgIGL/F/aIDqQb7xQ2vcrdIwxfjThSH8CSR7PBEakCr51Ck+w+/U6swU2Im1vVX0SVk9ABhg==\" crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\" />\n"
                      "    <style>\n"
                      "    body {\n"
                      "        background-color: #ffffff;\n"
                      "        font-family: \"PT Sans\", sans-serif;\n"
                      "        font-size: 16px;\n"
                      "        font-weight: normal;\n"
                      "        color: #424242;\n"
                      "        margin-left: 10px;\n"
                      "    }\n"
                      "    a {\n"
                      "        color: #366bcc;\n"
                      "        text-decoration: none;\n"
                      "        font-weight: bold;\n"
                      "        margin-left: 5px;\n"
                      "    }\n"
                      "    pre {\n"
                      "        font-size: small;\n"
                      "    }\n"
                      "    i {\n"
                      "        color: #1823c7;\n"
                      "    }\n"
                      "    [class*=\"lab-\"] {\n"
                      "        color: #070707;\n"
                      "        background: rgba(151, 177, 236, 0.97);\n"
                      "        font-family: \"PT sans\", sans-serif;\n"
                      "        font-size: 1rem;\n"
                      "        display: inline-block;\n"
                      "        width: 5rem;\n"
                      "        height: 20px;\n"
                      "        padding-left: 5px;\n"
                      "        margin-bottom: 5px;\n"
                      "    }\n"
                      "    .lab-left {\n"
                      "        text-align: left;\n"
                      "        width: 6rem;\n"
                      "        background: #ffffff;\n"
                      "    }\n"
                      "    .lab-right {\n"
                      "        text-align: right;\n"
                      "        width: 8rem;\n"
                      "    }\n"
                      "    .lab-data-left {\n"
                      "        text-align: left;\n"
                      "        width: 23rem;\n"
                      "        background: #FAFAFA;\n"
                      "        border: 1px solid #CCC;\n"
                      "    }\n"
                      "    .lab-data-right {\n"
                      "        text-align: right;\n"
                      "        width: 5rem;\n"
                      "        background: #FAFAFA;\n"
                      "        border: 1px solid #CCC;\n"
                      "    }\n"
                      "    .line {\n"
                      "        width: 25%;\n"
                      "        height: 0;\n"
                      "        border-bottom: 1px dotted #C4C4C4;\n"
                      "        margin: 3px;\n"
                      "        display:inline-block;\n"
                      "    }\n"
                      "    .line-gray {\n"
                      "        width: 15%;\n"
                      "        height: 0;\n"
                      "        border-bottom: 3px solid #C4C4C4;\n"
                      "        margin: 3px;\n"
                      "        display:inline-block;\n"
                      "    }\n"
                      "    </style>\n";
    
    char* html = malloc(4096 * sizeof(char)); // Allocate memory for the HTML string
    if (html == NULL) {
        return NULL; // Memory allocation failed
    }
    
    sprintf(html, "%s</head><body>Estimado(a) Senhor(a),"
                  "aceite desde já os nossos agradecimentos por utilizar o nosso site.<br>"
                  "Enviamos em anexo o ficheiro em Excel relativo ao ficheiro de inventário que nos foi/foram remetido(s).<br>"
                  "Esperando que o Excel por nós processado corresponda ás V/ espectativas.<br><br>"
                  "Sem outro assunto.<br>"
                  "Com os melhores cumprimentos,<br><br>"
                  "A Equipa de <a href=\"https://saftparaexcel.pt\">Saf-t para Excel</a> <br><br>"
                  "Em caso de dúvidas P.F. não responder a este e-mail "
                  "enviar um mail para o suporte: <a href=\"mailto:suporte@saftparaexcel.pt\">suporte@saftparaexcel.pt</a> mencionando a referencia:"
                  "C19-%s<div class=\"line\"></div>"
                  "<div><i class=\"fa-solid fa-file-excel fa-lg\" style=\"color:#33c482\"></i><a href=\"https://saftparaexcel.pt\">Saf-t para Excel</a></div>"
                  "<div><i class=\"fa-solid fa-file-excel fa-lg\" style=\"color: #175c37;\"></i><a href=\"https://saftparaexcel.pt\">Saf-t da contabilidade para Excel</a></div>"
                  "<div><i class=\"fa-solid fa-cubes-stacked fl-lg\" style=\"color: #9719b4;\"></i><a href=\"https://saftparaexcel.pt/#inventario-para-excel\">Inventário para Excel</a></div>"
                  "<div><i class=\"fa-solid fa-file-csv fl-lg\" style=\"color: #b2aa03;\"></i><a href=\"https://saftparaexcel.pt/#e-fatura-para-excel\">CSV do e-fatura para Excel</a></div>"
                  "<div class=\"line\"></div>", CSS, working_dir);
    
    return html;
}

